### ISSUE TITLE
Out-of-tree builds fail with missing nestegg/nestegg-stdint.h

### ISSUE THREAD

**Issue by brion** [kinetiknz/nestegg#28]
When trying to build outside the source tree, nestegg/nestegg-stdint.h can't be found and compilation fails:

```
In file included from ../nestegg/src/nestegg.c:12:
../nestegg/include/nestegg/nestegg.h:11:10: fatal error: 'nestegg/nestegg-stdint.h' file not found
#include <nestegg/nestegg-stdint.h>
```

Steps to reproduce:

1. git clone https://github.com/kinetiknz/nestegg.git
2. (cd nestegg && autoreconf --install)
3. (mkdir build && cd build && ../nestegg/configure)
4. (cd build && make)

**Comment by brion** [comment]
Looks like adding -I$(top_builddir)/include to the CPPFLAGS works the necessary magic.

**Comment by kinetiknz** [comment]
I just pushed db8617b to fix the regression tests in out-of-tree builds.

Thanks for the fix!
